apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: backend-workload
      containers:
      - name: backend
        image: acrhienplayground.azurecr.io/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        envFrom:
        - secretRef:
            name: app-secrets
        volumeMounts:
        - name: secrets
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "keyvault"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
