apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        # azure.workload.identity/use: "true"
    spec:
      # serviceAccountName: backend-workload
      containers:
      - name: backend
        image: acrhienplayground.azurecr.io/backend:latest
        ports:
        - containerPort: 3001
        # envFrom:
        # - secretRef:
        #     name: app-secrets
        # volumeMounts:
        # - name: secrets
        #   mountPath: "/mnt/secrets-store"
        #   readOnly: true
      # volumes:
      #   - name: secrets
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "keyvault"
