apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend
resources:
  - deployment.yaml
  - secret-provider-class.yaml
  - service-account.yaml
  - backend-scaling.yaml
  - consumer.yaml
  - consumer-scaling.yaml
  - keda-sb-authen.yaml
  - vpa.yaml
  - httproute.yaml