apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault
spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    clientID: "${id_keyvault}"
    keyvaultName: ${keyvault_name}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: my-secret
          objectType: secret
          objectVersion: "2caa3031b2b04dc48059a616a3055c9b"
        - |
          objectName: secret-2
          objectType: secret
          objectVersion: "2f94f11619ae4a8e86d3396f1a37183c"
    tenantId: ${tenant_id}

  secretObjects:
  - secretName: app-secrets
    type: Opaque
    data:
    - objectName: my-secret
      key: SECRET
    - objectName: secret-2
      key: SECRET2
