apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault
spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    tenantId: 5f431148-1e24-4600-af0b-cdaeeffa6045
    clientID: 33227015-4da3-46ae-8a17-050952d6529d
    keyvaultName: kv-playground-gw2y5h
    cloudName: ""
    objects: |
      array:
        - |
          objectName: my-secret
          objectType: secret
          objectVersion: "2caa3031b2b04dc48059a616a3055c9b"

  secretObjects:
  - secretName: app-secrets
    type: Opaque
    data:
    - objectName: my-secret
      key: SECRET
