apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault
spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    tenantId: ${AZURE_TENANT_ID}
    clientID: ${ID_BACKEND}
    keyvaultName: ${KEYVAULT_NAME}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: my-secret
          objectAlias: SECRET
          objectType: secret
          objectVersion: 769df6cf65df4108824f7605ad1de241
        - |
          objectName: my-secret-2
          objectAlias: SECRET_2
          objectType: secret
          objectVersion: d206562d35404932b0deaa8207bf73b0
